spring.application.name=findColor
server.port=8080

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/findcolor?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.web=INFO
logging.level.com.example.findcolor=DEBUG

# AWS S3 Configuration
cloud.aws.s3.bucket=image-upload-test-sdusdu
cloud.aws.region.static=ap-southeast-2
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
